#!/usr/bin/env python

import os
import sys

basedir = os.path.dirname(os.path.realpath(__file__))
old = os.path.join(basedir, "apss")
sys.path.insert(0, os.path.join(basedir, "src"))

import apss
apss.main()
